sudo: false
language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
env:
    - APP_ENV=test EXCLUDE_TEST_GROUPS=non_default_manager,multiple_managers COMPOSER_FLAGS= SYMFONY_VER=3.2.0
    - APP_ENV=test EXCLUDE_TEST_GROUPS=non_default_manager,multiple_managers COMPOSER_FLAGS= SYMFONY_VER=3.3.0
    - APP_ENV=test EXCLUDE_TEST_GROUPS=non_default_manager,multiple_managers COMPOSER_FLAGS=--prefer-lowest SYMFONY_VER=3.2.0
    - APP_ENV=test EXCLUDE_TEST_GROUPS=non_default_manager,multiple_managers COMPOSER_FLAGS=--prefer-lowest SYMFONY_VER=3.3.0
    - APP_ENV=non_default_manager EXCLUDE_TEST_GROUPS=test,multiple_managers COMPOSER_FLAGS= SYMFONY_VER=3.2.0
    - APP_ENV=non_default_manager EXCLUDE_TEST_GROUPS=test,multiple_managers COMPOSER_FLAGS= SYMFONY_VER=3.3.0
    - APP_ENV=non_default_manager EXCLUDE_TEST_GROUPS=test,multiple_managers COMPOSER_FLAGS=--prefer-lowest SYMFONY_VER=3.2.0
    - APP_ENV=non_default_manager EXCLUDE_TEST_GROUPS=test,multiple_managers COMPOSER_FLAGS=--prefer-lowest SYMFONY_VER=3.3.0
    - APP_ENV=multiple_managers EXCLUDE_TEST_GROUPS=test,non_default_manager COMPOSER_FLAGS= SYMFONY_VER=3.2.0
    - APP_ENV=multiple_managers EXCLUDE_TEST_GROUPS=test,non_default_manager COMPOSER_FLAGS= SYMFONY_VER=3.3.0
    - APP_ENV=multiple_managers EXCLUDE_TEST_GROUPS=test,non_default_manager COMPOSER_FLAGS=--prefer-lowest SYMFONY_VER=3.2.0
    - APP_ENV=multiple_managers EXCLUDE_TEST_GROUPS=test,non_default_manager COMPOSER_FLAGS=--prefer-lowest SYMFONY_VER=3.3.0

before_script:
    - |
        sed -i 's,"symfony/symfony": "\^2.8|\^3.0","symfony/symfony": "$SYMFONY_VER",g' composer.json
    - composer update $COMPOSER_FLAGS

script:
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff
    - ./vendor/bin/phpunit --exclude-group=$EXCLUDE_TEST_GROUPS
