sudo: false
language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
env:
    - APP_ENV=test EXCLUDE_TEST_GROUPS=non_default_manager,multiple_managers
    - APP_ENV=non_default_manager EXCLUDE_TEST_GROUPS=test,multiple_managers
    - APP_ENV=multiple_managers EXCLUDE_TEST_GROUPS=test,non_default_manager

before_script:
    - composer install

script:
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff
    - ./vendor/bin/phpunit --exclude-group=$EXCLUDE_TEST_GROUPS
